### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by catb0t** [factor/atom-language-factor#3]
Installing from Atom.io gives this error in Atom:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp http 200 https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp http GET https://atom.io/download/atom-shell/v0.36.8/SHASUMS256.txt
gyp http 200 https://atom.io/download/atom-shell/v0.36.8/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: node-v0.36.8.tar.gz local checksum 40c53a7302dede5d9887a95664e4b9061b4125e18774832021643dcfd555f042 not match remote undefined
gyp ERR! stack     at deref (/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/install.js:307:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/install.js:348:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:117:20)
gyp ERR! stack     at _stream_readable.js:944:16
gyp ERR! stack     at process._tickCallback (node.js:448:13)
gyp ERR! System Linux 4.2.0-31-generic
gyp ERR! command "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.36.8" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /home/cat/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

**Comment by mrjbq7** [comment]
That error seems like nothing to do with this syntax module.

It has some checksum error with `node-v0.36.8.tar.gz`?

**Comment by mrjbq7** [comment]
Suggestions from StackOverflow are to re-download node-v0.36.8.tar.gz or clear you npm cache `npm cache clean`.

**Comment by mrjbq7** [comment]
Maybe local network corruption.

**Comment by ForNeVeR** [comment]
I've just installed it to my Atom on Linux without problems. I was using the command `apm install language-factor`.

**Comment by catb0t** [comment]
Hmm, the checksums match when I download the files, and they also match when I `GET` the files the same way `npm` does, but npm still fails.
